# Simple workflow for deploying static content to GitHub Pages
name: Visualize repo

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@master
    - name: Update diagram
      id: make_diagram
      uses: githubocto/repo-visualizer@0.7.1
      with:
        output_file: "output-diagram.svg"
        artifact_name: "diagram"
        should_push: false
    - name: Get artifact
      uses: actions/download-artifact@v2
      with:
        name: "diagram"
        path: "downloads"
